apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-observer
  labels:
    service: k8s-observer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: k8s-observer
  template:
    metadata:
      labels:
        service: k8s-observer
    spec:
      containers:
        - name: k8s-observer
          image: docker.io/emunari/k8s-observer:latest
          ports:
            - containerPort: 5000
          env:
            - name: IN_CLUSTER
              value: "true"
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 5000
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 5000