apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

images:
- name: k8s-observer
  newName: emunari/k8s-observer
  newTag: 10640eb424294a549d97a8d249b46c94641dce23
