apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

images:
- name: k8s-observer
  newName: emunari/k8s-observer
  newTag: fd5951e5666bdaef4a77549589c4db4a50c6b371
