name: CD Workflow

on:
  push:
    branches: [appset-helm-deps]

jobs:
  build:
    name: Build and Push K8s Observer Image
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PASSWD}}
        repository: ${{secrets.DOCKERHUB_USER}}/k8s-observer
        tags: ${{github.sha}}, latest