name: CD Workflow

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Push K8s Observer Image
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PASSWD}}
        repository: ${{secrets.DOCKERHUB_USER}}/k8s-observer
        tags: ${{github.sha}}, latest

  update:
    name: Update K8s Observer k8s files
    needs: 
      - build
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.6.1"

    - name: Update Kubernetes Resources
      env:
        DOCKER_USERNAME: ${{secrets.DOCKERHUB_USER}}
      run: |
        cd k8s
        kustomize edit set image k8s-observer=$DOCKER_USERNAME/k8s-observer:$GITHUB_SHA

    - name: Commit new tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "[K8s Observer] Auto Trigger"
        git commit -am "Bump K8s Observer version"

    - name: Push
      uses: ad-m/github-push-action@master
      with: 
        repository: dumunari/k8s-observer
        github_token: ${{ secrets.GITHUB_TOKEN }}